name = "EllipticCoversOscar"
uuid = "8ad5aec1-3394-4e76-9fb4-62099650952a"
authors = ["Mohamed Abdellatif Kallel"]
version = "0.1.0"

[deps]
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]